### ISSUE TITLE
Nothing happens for Linux 64 target

### ISSUE THREAD

**Issue by ClaymorePT** [TylerJewell/che-electron#7]
I have done everything what the documentation demanded, but only one window opens, named Electron with background in white.

This was my procedure. What am I doing wrong?
```
npm install electron-packager -g
git clone http://github.com/tylerjewell/che-electron
cd che-electron
npm run pack:linux64
cd ./dist/eclipse-che-linux-x64
./eclipse-che . http://192.168.83.98:8000
```

**Comment by TylerJewell** [comment]
Hi @ClaymorePT - I'm sorry, but I am not maintaining this project anymore. The last time it was tested was against Che 4.x, and was never tested against the 5.x versions that exist now. There could be any number of problems that you are encountering.

Did you find a reference to this repo somewhere else?  I would like to remove those references so that others do not use this accidentally as I am unable to provide support for it now.

**Comment by ClaymorePT** [comment]
Yes. I have found the reference at the Official Eclipse-Che client page [here](http://www.eclipse.org/che/docs/ide/electron/index.html).
What can I do as an alternative?

**Comment by TylerJewell** [comment]
Thanks for the reference.  We will get it removed from the project pages. We are not aware of any other electron clients for Che right now.

**Comment by ClaymorePT** [comment]
Ok.
Thank you for the rapid response!
